// Shared reader/mapper for the monster data source: ragassets' mobs.json — one
// of the `/raw` tables, alongside the item/job ones (see tools/raw-source.mjs).
//
// One record per monster, generated by ragassets from the RagnaPlace Public API
// (laro-pt gateway) — i.e. LATAM server values. Public, no auth. This repo only
// ever *downloads the file*; it never calls the API itself.
//
// Source record shape:
//   { id, aegisId, name, boss, mvp, level, baseExp, jobExp, mvpExp, hp, def,
//     mdef, attack, str, agi, vit, int, dex, luk, race, size, property,
//     propertyLevel }
//
// `name` is pt-BR; `race`/`size`/`property` are English enums. `aegisId` is what
// monster.json calls `dbname`.
//
// NOT in the source: `res`/`mres` (the calc defaults both to 0 — see monster.ts)
// and the spawn map (monster.json's `spawn` is maintained by hand).

import { loadRawJson, readRawFile, RAW_BASE } from "./raw-source.mjs";

export const MOBS_URL = `${RAW_BASE}/mobs.json`;

/**
 * The calc's race vocabulary. `Monster.setData` lowercases `raceName` into the
 * `race` union, so these strings must match exactly ("DemiHuman", not "Human").
 */
export const RACE = ["Formless", "Undead", "Brute", "Plant", "Insect", "Fish", "Demon", "DemiHuman", "Angel", "Dragon"];
export const ELE = ["Neutral", "Water", "Earth", "Fire", "Wind", "Poison", "Holy", "Dark", "Ghost", "Undead"];
export const SIZE = { Small: 0, Medium: 1, Large: 2 };

/**
 * The source's `race` field is dirty upstream (RagnaPlace's own data, not a
 * transport artifact): most Formless mobs come through as the pt-BR word
 * "fantasma", and DemiHuman arrives under three spellings. Every mapping below
 * was checked against the races monster.json already held — "fantasma" agreed
 * with Formless on all 59 overlapping ids, "Human" with DemiHuman on its 1.
 *
 * Anything not listed here is a NEW upstream value: `normalizeRace` throws
 * rather than passing an unknown string into the calc, where it would silently
 * degrade to a race no bonus ever matches.
 */
export const RACE_NORMALIZATION = {
  Formless: "Formless",
  fantasma: "Formless",
  Undead: "Undead",
  Brute: "Brute",
  Plant: "Plant",
  Insect: "Insect",
  Fish: "Fish",
  Demon: "Demon",
  Angel: "Angel",
  Dragon: "Dragon",
  DemiHuman: "DemiHuman",
  Demihuman: "DemiHuman",
  "Demi-Human": "DemiHuman",
  Human: "DemiHuman",
};

export function normalizeRace(raw, id) {
  const mapped = RACE_NORMALIZATION[raw];
  if (!mapped) {
    throw new Error(
      `mob ${id}: unmapped race "${raw}" — add it to RACE_NORMALIZATION in tools/mob-source.mjs ` +
        `(known: ${Object.keys(RACE_NORMALIZATION).join(", ")})`,
    );
  }
  return mapped;
}

export function normalizeSize(raw, id) {
  if (!(raw in SIZE)) throw new Error(`mob ${id}: unmapped size "${raw}" — expected one of ${Object.keys(SIZE).join(", ")}`);
  return raw;
}

export function normalizeProperty(raw, id) {
  if (!ELE.includes(raw)) throw new Error(`mob ${id}: unmapped element "${raw}" — expected one of ${ELE.join(", ")}`);
  return raw;
}

/**
 * Download mobs.json, or read a local copy with --src — which takes either the
 * mobs.json path itself (the historical form) or a directory holding the /raw
 * tables.
 */
export async function loadMobs(src) {
  const arr = src?.endsWith(".json") ? readRawFile(src) : await loadRawJson("mobs.json", src);
  if (!Array.isArray(arr)) throw new Error("mobs.json: expected a JSON array of mob objects");
  return arr;
}

export function indexById(mobs) {
  const byId = new Map();
  for (const m of mobs) if (m && Number.isInteger(m.id)) byId.set(m.id, m);
  return byId;
}

/**
 * The fields of a monster.json record that `Monster.setData` actually reads —
 * everything else in the record is display-only or derived. Sourcing a value as
 * `null` here is never acceptable, so these drive the null policy below.
 */
export const CALC_READ_STAT_FIELDS = [
  "level", "health", "defense", "magicDefense", "res", "mres",
  "str", "agi", "vit", "int", "dex", "luk",
  "elementName", "raceName", "scaleName", "class", "mvp",
];

/**
 * Map a source record onto the monster.json `stats` fields this repo sources
 * from it, given the record we already have (or `{}` for a brand-new one).
 *
 * NULL POLICY — a null in the source means "RagnaPlace has no value", not zero.
 * A null never reaches the calc: the field keeps whatever the existing record
 * holds, and the retention is reported back to the caller so it can be logged.
 * For a new record there is nothing to fall back to, so the caller must treat a
 * retention on a `CALC_READ_STAT_FIELDS` entry as a hard failure.
 *
 * Returns `{ stats, retained }` where `stats` holds only the sourced fields.
 */
export function mapMobStats(mob, prevStats = {}) {
  const retained = [];
  const take = (field, value, prevKey = field) => {
    if (value == null) {
      retained.push(field);
      return prevStats[prevKey];
    }
    return value;
  };

  const stats = {
    level: take("level", mob.level),
    health: take("health", mob.hp),
    defense: take("defense", mob.def),
    magicDefense: take("magicDefense", mob.mdef),
    str: take("str", mob.str),
    agi: take("agi", mob.agi),
    vit: take("vit", mob.vit),
    int: take("int", mob.int),
    dex: take("dex", mob.dex),
    luk: take("luk", mob.luk),
    // `boss` is the boss protocol (immune to freeze/stun/…); `mvp` is the subset
    // that also drops an MVP reward. Verified as a strict subset in the source.
    class: mob.boss ? 1 : 0,
    mvp: mob.mvp ? 1 : 0,
  };

  const raceName = mob.race == null ? (retained.push("raceName"), prevStats.raceName) : normalizeRace(mob.race, mob.id);
  const scaleName = mob.size == null ? (retained.push("scaleName"), prevStats.scaleName) : normalizeSize(mob.size, mob.id);
  const property = mob.property == null ? null : normalizeProperty(mob.property, mob.id);
  // elementName is one string ("Dark 3"): it needs BOTH halves, so a null in
  // either one retains the previous elementName whole rather than half-updating.
  const hasElement = property != null && mob.propertyLevel != null;
  if (!hasElement) retained.push("elementName");
  const elementName = hasElement ? `${property} ${mob.propertyLevel}` : prevStats.elementName;
  const elementShortName = hasElement ? property : prevStats.elementShortName;

  stats.raceName = raceName;
  stats.scaleName = scaleName;
  stats.elementName = elementName;
  stats.elementShortName = elementShortName;

  // Numeric codes, kept for format parity with the rest of the file. The calc
  // ignores them and parses the name strings instead (see monster.ts).
  stats.race = raceName ? RACE.indexOf(raceName) : prevStats.race;
  stats.scale = scaleName ? SIZE[scaleName] : prevStats.scale;
  stats.element = elementName ? 20 * Number(elementName.split(" ")[1]) + ELE.indexOf(elementName.split(" ")[0]) : prevStats.element;

  return { stats, retained };
}
