import { EquipmentSummaryModel } from '../models/equipment-summary.model';

export const createRawTotalBonus = (): EquipmentSummaryModel => {
  return {
    refine: 0,
    weight: 0,

    hp: 0,
    hpPercent: 0,
    sp: 0,
    spPercent: 0,
    // Display only — see EquipmentSummaryModel.healReceived / .healPower.
    healReceived: 0,
    healPower: 0,
    hpRecovRate: 0,
    spRecovRate: 0,
    hpDrain: 0,
    spDrain: 0,
    reduceDamageReturn: 0,
    magicHealHp: 0,
    magicHealSp: 0,
    hpRestoreOnKill: 0,
    spRestoreOnKill: 0,
    def: 0,
    defPercent: 0,
    softDef: 0,
    softDefPercent: 0,
    mdef: 0,
    mdefPercent: 0,
    softMdef: 0,
    softMdefPercent: 0,
    aspd: 0,
    aspdPercent: 0,
    skillAspd: 0,
    skillAspdPercent: 0,
    decreaseSkillAspdPercent: 0,

    atk: 0,
    x_atk: 0,
    cannonballAtk: 0,
    atkPercent: 0,

    matk: 0,
    matkPercent: 0,
    allStatus: 0,

    str: 0,
    int: 0,
    dex: 0,
    luk: 0,
    vit: 0,
    agi: 0,

    allTrait: 0,
    pAtk: 0,
    sMatk: 0,
    pow: 0,
    sta: 0,
    wis: 0,
    spl: 0,
    con: 0,
    crt: 0,
    cRate: 0,
    hplus: 0,

    res: 0,
    monster_res: 0,
    mres: 0,
    monster_mres: 0,

    melee: 0,
    range: 0,
    bowRange: 0,
    vct: 0,
    vct_inc: 0,
    acd: 0,
    fct: 0,
    fctPercent: 0,
    cri: 0,
    // "CRIT à distância": crit rate that only counts on the BASIC attack, and only with a
    // ranged weapon. Kept apart from `cri` because `cri` feeds the skill crit rate too
    // (see damage-calculator getBaseCriRate / the skill branch), and this one must not.
    criRange: 0,
    criDmg: 0,
    perfectHit: 0,
    hit: 0,
    flee: 0,
    perfectDodge: 0,

    flatDmg: 0,
    mildwind: 0,
    dmg: 0,
    ignore_size_penalty: 0,
    p_infiltration: 0,

    p_size_all: 0,
    p_size_s: 0,
    p_size_m: 0,
    p_size_l: 0,

    p_element_all: 0,
    p_element_neutral: 0,
    p_element_water: 0,
    p_element_earth: 0,
    p_element_fire: 0,
    p_element_wind: 0,
    p_element_poison: 0,
    p_element_holy: 0,
    p_element_dark: 0,
    p_element_ghost: 0,
    p_element_undead: 0,

    p_race_all: 0,
    p_race_formless: 0,
    p_race_undead: 0,
    p_race_brute: 0,
    p_race_plant: 0,
    p_race_insect: 0,
    p_race_fish: 0,
    p_race_demon: 0,
    p_race_demihuman: 0,
    p_race_angel: 0,
    p_race_dragon: 0,
    p_race_player_human: 0,
    p_race_player_doram: 0,

    p_class_all: 0,
    p_class_normal: 0,
    p_class_boss: 0,

    pene_res: 0,
    pene_res_race_formless: 0,
    pene_res_race_undead: 0,
    pene_res_race_brute: 0,
    pene_res_race_plant: 0,
    pene_res_race_insect: 0,
    pene_res_race_fish: 0,
    pene_res_race_demon: 0,
    pene_res_race_demihuman: 0,
    pene_res_race_angel: 0,
    pene_res_race_dragon: 0,
    pene_res_race_player_human: 0,
    pene_res_race_player_doram: 0,

    pene_mres: 0,
    pene_mres_race_formless: 0,
    pene_mres_race_undead: 0,
    pene_mres_race_brute: 0,
    pene_mres_race_plant: 0,
    pene_mres_race_insect: 0,
    pene_mres_race_fish: 0,
    pene_mres_race_demon: 0,
    pene_mres_race_demihuman: 0,
    pene_mres_race_angel: 0,
    pene_mres_race_dragon: 0,
    pene_mres_race_player_human: 0,
    pene_mres_race_player_doram: 0,


    p_pene_class_all: 0,
    p_pene_class_normal: 0,
    p_pene_class_boss: 0,

    p_pene_race_all: 0,
    p_pene_race_formless: 0,
    p_pene_race_undead: 0,
    p_pene_race_brute: 0,
    p_pene_race_plant: 0,
    p_pene_race_insect: 0,
    p_pene_race_fish: 0,
    p_pene_race_demon: 0,
    p_pene_race_demihuman: 0,
    p_pene_race_angel: 0,
    p_pene_race_dragon: 0,
    p_pene_race_player_human: 0,
    p_pene_race_player_doram: 0,

    m_size_all: 0,
    m_size_s: 0,
    m_size_m: 0,
    m_size_l: 0,

    m_my_element_all: 0,
    m_my_element_neutral: 0,
    m_my_element_water: 0,
    m_my_element_earth: 0,
    m_my_element_fire: 0,
    m_my_element_wind: 0,
    m_my_element_poison: 0,
    m_my_element_holy: 0,
    m_my_element_dark: 0,
    m_my_element_ghost: 0,
    m_my_element_undead: 0,

    m_element_all: 0,
    m_element_neutral: 0,
    m_element_water: 0,
    m_element_earth: 0,
    m_element_fire: 0,
    m_element_wind: 0,
    m_element_poison: 0,
    m_element_holy: 0,
    m_element_dark: 0,
    m_element_ghost: 0,
    m_element_undead: 0,

    m_race_all: 0,
    m_race_formless: 0,
    m_race_undead: 0,
    m_race_brute: 0,
    m_race_plant: 0,
    m_race_insect: 0,
    m_race_fish: 0,
    m_race_demon: 0,
    m_race_demihuman: 0,
    m_race_angel: 0,
    m_race_dragon: 0,
    m_race_player_human: 0,
    m_race_player_doram: 0,

    m_class_all: 0,
    m_class_normal: 0,
    m_class_boss: 0,

    m_pene_class_all: 0,
    m_pene_class_boss: 0,
    m_pene_class_normal: 0,

    m_pene_race_all: 0,
    m_pene_race_undead: 0,
    m_pene_race_plant: 0,
    m_pene_race_insect: 0,
    m_pene_race_formless: 0,
    m_pene_race_fish: 0,
    m_pene_race_dragon: 0,
    m_pene_race_player_human: 0,
    m_pene_race_player_doram: 0,
    m_pene_race_demon: 0,
    m_pene_race_demihuman: 0,
    m_pene_race_brute: 0,
    m_pene_race_angel: 0,

    // Defender-side reductions (PVP) — see docs/pvp.md §4
    dmg_taken_physical: 0,
    dmg_taken_magical: 0,
    dmg_taken_all: 0,
    dmg_taken_range: 0,

    subele_all: 0,
    subele_neutral: 0,
    subele_water: 0,
    subele_earth: 0,
    subele_fire: 0,
    subele_wind: 0,
    subele_poison: 0,
    subele_holy: 0,
    subele_dark: 0,
    subele_ghost: 0,
    subele_undead: 0,

    subsize_all: 0,
    subsize_s: 0,
    subsize_m: 0,
    subsize_l: 0,

    subsize_all_physical: 0,
    subsize_s_physical: 0,
    subsize_m_physical: 0,
    subsize_l_physical: 0,

    subsize_all_magical: 0,
    subsize_s_magical: 0,
    subsize_m_magical: 0,
    subsize_l_magical: 0,

    subclass_all: 0,
    subclass_normal: 0,
    subclass_boss: 0,

    subrace_all: 0,
    subrace_formless: 0,
    subrace_undead: 0,
    subrace_brute: 0,
    subrace_plant: 0,
    subrace_insect: 0,
    subrace_fish: 0,
    subrace_demon: 0,
    subrace_demihuman: 0,
    subrace_angel: 0,
    subrace_dragon: 0,
    subrace_player_human: 0,
    subrace_player_doram: 0,
  };
};
